name: Wails Build

on:
  push:
    tags:
      - "*"
      
  workflow_dispatch:

jobs:

  build:
    runs-on: macos-latest
    steps:
    
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 17.4.0
        
    # - name: Install XCode Select
    #   run: xcode-select --install
      
    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
    
    - name: Wails CLI Build
      run: wails build -clean -f
      
    - name: Create Build Folder & DMG
      run: |
        mv build/bin build/wiggler
        hdiutil create -srcfolder build/wiggler wiggler-${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}.dmg
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wiggler-${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}
        path: wiggler-${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}.dmg
        
    
